import telebot
from telebot import types
import text
import time
import random
import key
bot = telebot.TeleBot(key.key)
markup = types.ReplyKeyboardMarkup()
markup2 = types.ReplyKeyboardMarkup()
markup3 = types.ReplyKeyboardMarkup()
markup4 = types.ReplyKeyboardMarkup()
buttonA = types.KeyboardButton('Хочу сердешко..')
buttonB = types.KeyboardButton('Хочу чего-то милого..')
buttonC = types.KeyboardButton('Хочу немного поддержки..')
buttonE = types.KeyboardButton('Хочу еще милого..')
buttonS = types.KeyboardButton('/start')
buttonH = types.KeyboardButton('/help')
buttonEx = types.KeyboardButton('Пока хватит, спасибо..')
buttonMa = types.KeyboardButton("Ты выйдешь за меня?..")
buttonHelpr = types.KeyboardButton("Еще хочу немного поддержки..")
markup.row(buttonA,buttonB,buttonC,buttonMa)
markup2.row(buttonS,buttonH)
markup3.row(buttonE,buttonEx)
markup4.row(buttonHelpr,buttonEx)
print("RUN")
def def_love(message):  #❤️🧡💛💚💙💜🤎🖤
    z=0.3
    messagetoedit = bot.send_message(message.chat.id, text.T[0])
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text= text.T[1])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[2])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[3])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[4])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[5])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[6])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[7])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[8])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[9])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[10])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[11])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[12])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[13])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[14])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[15])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[16])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[17])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[18])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[19])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[20])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[21])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[22])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[23])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[24])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[25])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[26])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[27])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[28])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[29])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[30])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[31])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[32])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[33])
    time.sleep(z)
    bot.edit_message_text(chat_id=message.chat.id, message_id=messagetoedit.message_id, text=text.T[34])
    time.sleep(z)
    bot.send_message(message.chat.id, text="Люблю тебя , зайка❤️")
@bot.message_handler(content_types=['text'])
def get_text_messages(message):
    if message.text == "/start" or message.text == "Пока хватит, спасибо..":
        print(str(message.from_user.id) + ">>" + str(message.from_user.first_name)+" "+ str(message.from_user.last_name) + ">>" + str(message.text))
        bot.send_message(message.from_user.id, "Хочешь чего-нибудь милого?)",reply_markup=markup)
    elif message.text == "/help":
        print(str(message.from_user.id) + ">>" + str(message.from_user.first_name)+" "+ str(message.from_user.last_name) + ">>" + str(message.text))
        bot.send_message(message.from_user.id, "Привет,я могу поддержать тебя в любую минуту, если тебе грустно или тяжело")
        bot.send_message(message.from_user.id, "Могу отправить тебе волшебное чердечко или написать милые вещи, если ты захочешь)")
        bot.send_message(message.from_user.id, "Для начала нажми на /start для выбора, чего ты хочешь <3",reply_markup=markup2)
    elif message.text == "Хочу сердешко..":
        print(str(message.from_user.id) + ">>" + str(message.from_user.first_name)+" "+ str(message.from_user.last_name) + ">>" + str(message.text))
        def_love(message)
    elif message.text == "Ты выйдешь за меня?..":
        print(str(message.from_user.id) + ">>" + str(message.from_user.first_name)+" "+ str(message.from_user.last_name) + ">>" + str(message.text))
        bot.send_message(message.from_user.id, "Да, конечно!!")
    #стикер кольца https://qna.habr.com/q/1030694
    elif message.text == "Хочу чего-то милого.." or message.text == "Хочу еще милого..":
        print(str(message.from_user.id) + ">>" + str(message.from_user.first_name)+" "+ str(message.from_user.last_name) + ">>" + str(message.text))
        bot.send_message(message.from_user.id, random.choice(text.T2),reply_markup=markup3)
    elif message.text == "Хочу немного поддержки.." or message.text == "Еще хочу немного поддержки..":
        print(str(message.from_user.id) + ">>" + str(message.from_user.first_name)+" "+ str(message.from_user.last_name) + ">>" + str(message.text))
        bot.send_message(message.from_user.id, random.choice(text.T3),reply_markup=markup4)
    else:
        print(str(message.from_user.id) + ">>" + str(message.from_user.first_name)+" "+ str(message.from_user.last_name) + ">>" + str(message.text))
        bot.send_message(message.from_user.id, "Я тебя не понимаю... Напиши пожалуйста /start",reply_markup=markup2)

while True:
    try:
        bot.polling(none_stop=True, interval=0)
    except Exception as e:
        print(e)
        #подключить логер
        time.sleep(15)
